[workspace]
resolver = "2"
members = ["doppler", "sdk", "program", "program-extended", "examples"]

[workspace.package]
repository = "https://github.com/blueshift-gg/doppler"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
doppler = { path = "doppler" }
doppler-sdk = { path = "sdk" }
bs58 = "0.5"
bytemuck = { version = "1", features = ["derive"] }
mollusk-svm = "0.15"
mollusk-svm-bencher = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.11"
solana-account = "4"
solana-client = "4"
solana-compute-budget-interface = "3"
solana-define-syscall = "5.2"
solana-hash = "4"
solana-instruction = "3"
solana-keypair = "3"
solana-loader-v3-interface = { version = "~8.0", features = ["wincode"] }
solana-message = "4"
solana-pubkey = { version = "4", features = ["curve25519", "sha2"] }
solana-rent = "4"
solana-sdk-ids = "3"
solana-signature = "3"
solana-signer = "3"
solana-system-interface = { version = "3", features = ["bincode"] }
solana-transaction = "4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
