#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  createGeneratorConfig,
  type ConfigOverrides,
  type SbpfArch,
} from "@blueshift-gg/doppler-core";
import { Keypair } from "@solana/web3.js";
import { Command, InvalidArgumentError } from "commander";

import { loadGeneratorConfigInput } from "./config.js";
import { deployProgram } from "./deploy.js";
import { renderInitSchemaFile, writeDopplerArtifacts } from "./emit.js";
import { DEFAULT_SOLANA_CONFIG_PATH } from "./solana-config.js";

type GenerateArgs = {
  schemaFile: string;
  name: string;
  bytecodeFile?: string;
  web3jsSdkDir?: string;
  kitSdkDir?: string;
  rustSdkDir?: string;
  manifestFile?: string;
  assemblyFile?: string;
  keysDir: string;
  overrides: ConfigOverrides;
};

type InitOptions = {
  out?: string;
};

type DeployOptions = {
  programKeypair: string;
  admin: string;
  signer?: string;
  network?: string;
  config?: string;
};

type GeneratedKeypair = {
  role: "program" | "admin";
  publicKey: string;
  file: string;
};

async function main(): Promise<void> {
  const program = createCommand();
  await program.parseAsync(process.argv);
}

export function createCommand(): Command {
  const program = new Command()
    .name("doppler")
    .description("Generate and deploy custom Doppler bytecode and SDK files from a payload schema")
    .showHelpAfterError();

  program
    .command("init")
    .description("Create a starter payload schema file")
    .option("--out <file>", "Schema output filepath", "payload.ts")
    .addHelpText(
      "after",
      `
Writes only the payload schema. Does not create keypairs or manifest.json.
`,
    )
    .action(async (options: InitOptions) => {
      await runInit(options);
    });

  program
    .command("generate")
    .description("Generate compiled Doppler bytecode and optional SDK files")
    .argument("<schema-file>", "Path to TypeScript, JavaScript, or JSON payload schema")
    .argument("[name]", "Generated artifact name", "doppler")
    .option(
      "--bytecode <file>",
      "Output filepath for compiled Doppler bytecode. Defaults to ./<name>.so",
    )
    .option("--web3js-sdk <directory>", "Output directory for generated @solana/web3.js SDK")
    .option("--kit-sdk <directory>", "Output directory for generated @solana/kit SDK")
    .option("--rust-sdk <directory>", "Output directory for generated Rust SDK")
    .option(
      "--manifest <file>",
      "Output filepath for manifest JSON. Defaults to manifest.json next to bytecode output",
    )
    .option("--assembly <file>", "Output filepath for generated assembly source")
    .option("--arch <arch>", "Target sBPF arch. Defaults to v3", parseArch)
    .option(
      "--program-id <address>",
      "Program ID override. Defaults to manifest.json or a generated program keypair",
    )
    .option(
      "--admin <address>",
      "Admin address override. Defaults to manifest.json or a generated admin keypair",
    )
    .option("--keys-dir <directory>", "Directory for generated keypair files", "keys")
    .addHelpText(
      "after",
      `
Does not modify the input schema file.
If programId or admin are missing from manifest.json and CLI flags, keypair files are
created under --keys-dir and their public keys are written to manifest.json.
Subsequent runs reuse programId and admin from manifest.json in the schema file directory.
`,
    )
    .action(async (schemaFile: string, name: string, options: GenerateCommandOptions) => {
      await runGenerate(toGenerateArgs(schemaFile, name, options));
    });

  program
    .command("deploy")
    .description("Deploy compiled Doppler bytecode to a Solana cluster")
    .argument("<bytecode-file>", "Path to compiled Doppler bytecode (.so)")
    .requiredOption("--program-keypair <file>", "Path to the program keypair JSON file")
    .requiredOption("--admin <address>", "Admin address embedded in the generated bytecode")
    .option(
      "--signer <file>",
      "Signer keypair for deployment fees. Defaults to keypair_path in Solana CLI config",
    )
    .option(
      "--network <url>",
      "RPC URL for deployment. Defaults to json_rpc_url in Solana CLI config",
    )
    .option("--config <file>", `Solana CLI config file. Defaults to ${DEFAULT_SOLANA_CONFIG_PATH}`)
    .addHelpText(
      "after",
      `
If manifest.json sits next to the bytecode file, deploy verifies that admin and programId match.
`,
    )
    .action(async (bytecodeFile: string, options: DeployOptions) => {
      await runDeploy(bytecodeFile, options);
    });

  program.action(() => {
    program.help();
  });

  return program;
}

async function runInit(options: InitOptions): Promise<void> {
  const schemaFile = resolve(options.out ?? "payload.ts");

  await writeFileEnsuringDir(schemaFile, renderInitSchemaFile({ price: "u64" }));

  console.log(`Created schema: ${schemaFile}`);
}

async function runGenerate(args: GenerateArgs): Promise<void> {
  const loaded = await loadGeneratorConfigInput(args.schemaFile);

  const slug = slugify(args.name);
  const bytecodeFile = args.bytecodeFile ?? `./${slug}.so`;
  const generatedKeypairs: GeneratedKeypair[] = [];
  const overrides: ConfigOverrides = {
    ...args.overrides,
    name: args.name,
    programId:
      args.overrides.programId ??
      loaded.programId ??
      (await generateKeypair("program", slug, args.keysDir, generatedKeypairs)),
    admin:
      args.overrides.admin ??
      loaded.admin ??
      (await generateKeypair("admin", slug, args.keysDir, generatedKeypairs)),
  };

  const config = createGeneratorConfig(loaded, overrides);
  const manifest = await writeDopplerArtifacts(config, {
    bytecodeFile,
    ...(args.web3jsSdkDir ? { web3jsSdkDir: args.web3jsSdkDir } : {}),
    ...(args.kitSdkDir ? { kitSdkDir: args.kitSdkDir } : {}),
    ...(args.rustSdkDir ? { rustSdkDir: args.rustSdkDir } : {}),
    ...(args.manifestFile ? { manifestFile: args.manifestFile } : {}),
    ...(args.assemblyFile ? { assemblyFile: args.assemblyFile } : {}),
  });

  console.log(
    `Generated ${manifest.name} (${manifest.arch}, ${manifest.payloadSize} byte payload)`,
  );
  console.log(`Compiled bytecode: ${bytecodeFile}`);
  printGeneratedOutputs(args);
  printGeneratedKeypairs(generatedKeypairs);
}

async function runDeploy(bytecodeFile: string, options: DeployOptions): Promise<void> {
  const result = await deployProgram({
    bytecodePath: bytecodeFile,
    programKeypairPath: options.programKeypair,
    admin: options.admin,
    ...(options.signer ? { signerKeypairPath: options.signer } : {}),
    ...(options.network ? { network: options.network } : {}),
    ...(options.config ? { configPath: options.config } : {}),
  });

  // last signature is DeployWithMaxDataLen transaction
  console.log(`Deployed program: ${result.signatures[result.signatures.length - 1]}`);
}

function printGeneratedOutputs(args: GenerateArgs): void {
  if (args.assemblyFile) {
    console.log(`Assembly source: ${args.assemblyFile}`);
  }

  if (args.manifestFile) {
    console.log(`Manifest: ${args.manifestFile}`);
  }

  if (args.web3jsSdkDir) {
    console.log(`Web3.js SDK: ${args.web3jsSdkDir}`);
  }

  if (args.kitSdkDir) {
    console.log(`Kit SDK: ${args.kitSdkDir}`);
  }

  if (args.rustSdkDir) {
    console.log(`Rust SDK: ${args.rustSdkDir}`);
  }
}

function printGeneratedKeypairs(generatedKeypairs: GeneratedKeypair[]): void {
  for (const keypair of generatedKeypairs) {
    console.log(`Generated ${keypair.role} keypair: ${keypair.file} (${keypair.publicKey})`);
  }
  if (generatedKeypairs.length > 0) {
    console.log("Keep generated keypair files secure; the admin key controls oracle updates.");
  }
}

async function generateKeypair(
  role: "program" | "admin",
  slug: string,
  keysDir: string,
  generatedKeypairs: GeneratedKeypair[],
): Promise<string> {
  const keypair = await Keypair.generate();
  const file = resolve(keysDir, `${slug}-${role}-keypair.json`);
  await writeFileEnsuringDir(file, `${JSON.stringify(Array.from(keypair.secretKey))}\n`);

  const publicKey = keypair.publicKey.toBase58();
  generatedKeypairs.push({ role, publicKey, file });
  return publicKey;
}

async function writeFileEnsuringDir(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

type GenerateCommandOptions = {
  bytecode?: string;
  web3jsSdk?: string;
  kitSdk?: string;
  rustSdk?: string;
  manifest?: string;
  assembly?: string;
  arch?: SbpfArch;
  programId?: string;
  admin?: string;
  keysDir: string;
};

function toGenerateArgs(
  schemaFile: string,
  name: string,
  options: GenerateCommandOptions,
): GenerateArgs {
  const overrides: ConfigOverrides = {
    ...(options.arch ? { arch: options.arch } : {}),
    ...(options.programId ? { programId: options.programId } : {}),
    ...(options.admin ? { admin: options.admin } : {}),
  };

  return {
    schemaFile,
    name,
    ...(options.bytecode ? { bytecodeFile: options.bytecode } : {}),
    ...(options.web3jsSdk ? { web3jsSdkDir: options.web3jsSdk } : {}),
    ...(options.kitSdk ? { kitSdkDir: options.kitSdk } : {}),
    ...(options.rustSdk ? { rustSdkDir: options.rustSdk } : {}),
    ...(options.manifest ? { manifestFile: options.manifest } : {}),
    ...(options.assembly ? { assemblyFile: options.assembly } : {}),
    keysDir: options.keysDir,
    overrides,
  };
}

function parseArch(value: string): SbpfArch {
  if (value !== "v0" && value !== "v3") {
    throw new InvalidArgumentError("expected 'v0' or 'v3'");
  }
  return value;
}

function slugify(value: string): string {
  const slug = value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return slug || "doppler";
}

const isCliEntryPoint =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isCliEntryPoint) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
