use std::path::PathBuf;

use agave_feature_set::enable_sbpf_v3_deployment_and_execution;
use litesvm::LiteSVM;
use solana_native_token::LAMPORTS_PER_SOL;
use doppler_integration_sdk::{Oracle, PriceFeedIntegrationPayload, UpdateInstruction, BYTECODE, ID};
use solana_account::ReadableAccount;
use solana_keypair::Keypair;
use solana_pubkey::Pubkey;
use solana_signer::EncodableKey;
use solana_signer::Signer;
use solana_system_interface::instruction::create_account_with_seed;
use solana_transaction::Transaction;

fn admin_keypair() -> Keypair {
    let keypair_path: PathBuf = [
        env!("CARGO_MANIFEST_DIR"),
        "..",
        "..",
        "..",
        "examples",
        "keys",
        "admin-keypair.json",
    ]
    .iter()
    .collect();

    Keypair::read_from_file(keypair_path).expect("failed to read admin keypair fixture")
}

#[test]
fn deploy_program_then_create_and_update_oracle() {
    let admin = admin_keypair();
    let seed = "SOL-USDC";
    let oracle_key = Pubkey::create_with_seed(&admin.pubkey(), seed, &ID).expect("oracle PDA");

    let mut features = LiteSVM::mainnet_feature_set();
    features.activate(&enable_sbpf_v3_deployment_and_execution::id(), 0);

    let mut svm = LiteSVM::default()
        .with_feature_set(features)
        .with_builtins()
        .with_lamports(1_000_000u64.wrapping_mul(LAMPORTS_PER_SOL))
        .with_sysvars()
        .with_feature_accounts()
        .with_default_programs()
        .with_sigverify(true)
        .with_blockhash_check(true);
    svm.add_program(ID, BYTECODE)
        .expect("failed to deploy generated bytecode");
    svm.airdrop(&admin.pubkey(), 10_000_000_000)
        .expect("failed to fund admin");

    let oracle_size = core::mem::size_of::<Oracle<PriceFeedIntegrationPayload>>();
    let lamports = svm.minimum_balance_for_rent_exemption(oracle_size);

    let create_ix = create_account_with_seed(
        &admin.pubkey(),
        &oracle_key,
        &admin.pubkey(),
        seed,
        lamports,
        oracle_size as u64,
        &ID,
    );

    let create_tx = Transaction::new_signed_with_payer(
        &[create_ix],
        Some(&admin.pubkey()),
        &[&admin],
        svm.latest_blockhash(),
    );
    svm.send_transaction(create_tx)
        .expect("create oracle account transaction should succeed");

    let created = svm.get_account(&oracle_key).expect("oracle account should exist");
    assert_eq!(created.data().len(), oracle_size);
    assert_eq!(
        Oracle::<PriceFeedIntegrationPayload>::from_bytes(created.data()).sequence,
        0
    );

    let updated_oracle = Oracle::<PriceFeedIntegrationPayload> {
        sequence: 1,
        payload: PriceFeedIntegrationPayload { price: 1_100_000 },
    };

    let update_ix = UpdateInstruction {
        admin: admin.pubkey(),
        oracle_pubkey: oracle_key,
        oracle: updated_oracle,
    }
    .into();

    let update_tx = Transaction::new_signed_with_payer(
        &[update_ix],
        Some(&admin.pubkey()),
        &[&admin],
        svm.latest_blockhash(),
    );

    svm.send_transaction(update_tx)
        .expect("oracle update transaction should succeed");

    let account = svm
        .get_account(&oracle_key)
        .expect("oracle account should still exist");
    let oracle = Oracle::<PriceFeedIntegrationPayload>::from_bytes(account.data());

    assert_eq!(oracle.sequence, 1);
    assert_eq!(oracle.payload.price, 1_100_000);
}
